{'Input': {'szam': 2}, 'output': 'jegesmedve', 'teamID': [], 'channelID': {'id': 'api.context.404.app_error', 'message': 'Sorry, we could not find the page.', 'detailed_error': "There doesn't appear to be an api call for the url='/api/v4/teams/[]/channels'.", 'status_code': 404}}
{'Input': {'noveny': 'fenyo', 'allat': 'jegesmedve'}, 'output': {'noveny': 'ez egy fenyo', 'allat': 'ez egy jegesmedve', 'szin': 'zold'}, 'teamID': [], 'channelID': {'id': 'api.context.404.app_error', 'message': 'Sorry, we could not find the page.', 'detailed_error': "There doesn't appear to be an api call for the url='/api/v4/teams/[]/channels'.", 'status_code': 404}}
{'Input': {'szin': 'zold'}, 'output': 'ZOLD', 'teamID': [], 'channelID': {'id': 'api.context.404.app_error', 'message': 'Sorry, we could not find the page.', 'detailed_error': "There doesn't appear to be an api call for the url='/api/v4/teams/[]/channels'.", 'status_code': 404}}
